# Generated by Django 4.2.17 on 2026-01-17 07:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название класса')),
                ('graduation_class', models.IntegerField(blank=True, choices=[(4, '4'), (9, '9'), (11, '11')], null=True, verbose_name='Выпускной класс')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('basic', 'Базовый'), ('advanced', 'Повышенный')], default='basic', max_length=20, verbose_name='Уровень')),
                ('group_number', models.PositiveIntegerField(default=1, verbose_name='Номер подгруппы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='core.class', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Подгруппа для предмета в классе',
                'verbose_name_plural': 'Подгруппы для предметов в классах',
                'ordering': ['class_obj', 'subject', 'group_number'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название школы')),
                ('director', models.CharField(max_length=255, verbose_name='ФИО директора')),
                ('graduation_class', models.IntegerField(choices=[(4, '4'), (9, '9'), (11, '11')], verbose_name='Выпускной класс')),
                ('location', models.TextField(verbose_name='Расположение/адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('education_dept_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь отдела образования')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.class', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Учащийся',
                'verbose_name_plural': 'Учащиеся',
                'ordering': ['last_name', 'first_name', 'patronymic'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название предмета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superuser', 'Superuser'), ('education_dept', 'Отдел образования'), ('school_admin', 'Администратор школы')], default='school_admin', max_length=20, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_admin_profiles', to='core.school', verbose_name='Школа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'ordering': ['last_name', 'first_name', 'patronymic'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_group_links', to='core.student', verbose_name='Учащийся')),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='core.classsubjectgroup', verbose_name='Подгруппа')),
            ],
            options={
                'verbose_name': 'Распределение учащегося по подгруппе',
                'verbose_name_plural': 'Распределения учащихся по подгруппам',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('q1', 'Первая четверть'), ('q2', 'Вторая четверть'), ('q3', 'Третья четверть'), ('q4', 'Четвертая четверть'), ('exam', 'Экзаменационная'), ('year', 'Годовая'), ('final', 'Итоговая')], max_length=10, verbose_name='Период')),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.student', verbose_name='Учащийся')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['student', 'subject', 'quarter'],
            },
        ),
        migrations.AddField(
            model_name='classsubjectgroup',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subject_groups', to='core.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='classsubjectgroup',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='class_subject_groups', to='core.teacher', verbose_name='Учителя'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.school', verbose_name='Школа'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Редактирование'), ('delete', 'Удаление')], max_length=10, verbose_name='Действие')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='ID объекта')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал действий',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='studentsubjectgroup',
            constraint=models.UniqueConstraint(fields=('student', 'subject_group'), name='uniq_student_subject_group'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'quarter'), name='uniq_grade_per_period'),
        ),
        migrations.AddConstraint(
            model_name='classsubjectgroup',
            constraint=models.UniqueConstraint(fields=('class_obj', 'subject', 'group_number'), name='uniq_subject_group_number'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_class_name_per_school'),
        ),
    ]
