# Generated by ChatGPT on 2026-01-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("principal", models.CharField(blank=True, max_length=255)),
                ("graduation_class", models.CharField(blank=True, max_length=64)),
                ("location", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Школа",
                "verbose_name_plural": "Школы",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "school",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subjects", to="school_admin.school"),
                ),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
                "unique_together": {("school", "name")},
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=32)),
                (
                    "school",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="classes", to="school_admin.school"),
                ),
            ],
            options={
                "verbose_name": "Класс",
                "verbose_name_plural": "Классы",
                "unique_together": {("school", "name")},
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("middle_name", models.CharField(blank=True, max_length=150)),
                (
                    "school",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="teachers", to="school_admin.school"),
                ),
            ],
            options={
                "verbose_name": "Учитель",
                "verbose_name_plural": "Учителя",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("middle_name", models.CharField(blank=True, max_length=150)),
                (
                    "school_class",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="students", to="school_admin.schoolclass"),
                ),
            ],
            options={
                "verbose_name": "Учащийся",
                "verbose_name_plural": "Учащиеся",
            },
        ),
        migrations.CreateModel(
            name="ClassTeacherAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "study_level",
                    models.CharField(
                        choices=[("basic", "Базовый"), ("advanced", "Повышенный")],
                        default="basic",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school_class",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="school_admin.schoolclass"),
                ),
                (
                    "subject",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="school_admin.subject"),
                ),
                (
                    "teacher",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="school_admin.teacher"),
                ),
            ],
            options={
                "verbose_name": "Назначение учителя",
                "verbose_name_plural": "Назначения учителей",
            },
        ),
        migrations.CreateModel(
            name="AssignmentStudent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "study_level",
                    models.CharField(choices=[("basic", "Базовый"), ("advanced", "Повышенный")], max_length=16),
                ),
                (
                    "assignment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="student_links", to="school_admin.classteacherassignment"),
                ),
                (
                    "school_class",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignment_student_links", to="school_admin.schoolclass"),
                ),
                (
                    "student",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignment_links", to="school_admin.student"),
                ),
                (
                    "subject",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignment_student_links", to="school_admin.subject"),
                ),
            ],
            options={
                "verbose_name": "Участник подгруппы",
                "verbose_name_plural": "Участники подгрупп",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "quarter",
                    models.CharField(
                        choices=[
                            ("q1", "Первая"),
                            ("q2", "Вторая"),
                            ("q3", "Третья"),
                            ("q4", "Четвертая"),
                            ("exam", "Экзаменационная"),
                            ("year", "Годовая"),
                            ("final", "Итоговая"),
                        ],
                        max_length=16,
                    ),
                ),
                ("grade", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="grades", to="school_admin.classteacherassignment"),
                ),
                (
                    "student",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="grades", to="school_admin.student"),
                ),
            ],
            options={
                "verbose_name": "Оценка",
                "verbose_name_plural": "Оценки",
            },
        ),
        migrations.CreateModel(
            name="SchoolAdminProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "school",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="admins", to="school_admin.school"),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="school_admin_profile", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Администратор школы",
                "verbose_name_plural": "Администраторы школ",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(choices=[("CREATE", "CREATE"), ("UPDATE", "UPDATE"), ("DELETE", "DELETE")], max_length=16),
                ),
                ("model", models.CharField(max_length=128)),
                ("object_id", models.CharField(max_length=64)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_logs", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Лог действий",
                "verbose_name_plural": "Логи действий",
            },
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(fields=["school", "last_name", "first_name"], name="teacher_school_name_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["school_class", "last_name", "first_name"], name="student_class_name_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["created_at"], name="auditlog_created_at_idx"),
        ),
        migrations.AddConstraint(
            model_name="classteacherassignment",
            constraint=models.UniqueConstraint(fields=("school_class", "subject", "teacher", "study_level"), name="uniq_assignment_per_teacher"),
        ),
        migrations.AddConstraint(
            model_name="assignmentstudent",
            constraint=models.UniqueConstraint(fields=("assignment", "student"), name="uniq_student_per_assignment"),
        ),
        migrations.AddConstraint(
            model_name="assignmentstudent",
            constraint=models.UniqueConstraint(fields=("student", "school_class", "subject", "study_level"), name="uniq_student_per_class_subject_level"),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(fields=("student", "assignment", "quarter"), name="uniq_grade"),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.CheckConstraint(check=models.Q(grade__isnull=True) | models.Q(grade__gte=1, grade__lte=10), name="grade_1_10"),
        ),
    ]
