# Generated by Django 6.0 on 2025-12-12 14:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Reward Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('points_required', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Points Required')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rewarded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, verbose_name='User Name')),
                ('user_email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('points_used', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Points Used')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewarded_items', to='rewards.reward', verbose_name='Reward')),
            ],
            options={
                'verbose_name': 'Rewarded Item',
                'verbose_name_plural': 'Rewarded Items',
                'ordering': ['-requested_at'],
            },
        ),
    ]
